### ISSUE TITLE
Bug in production from using Esnext + vite

### ISSUE THREAD

**Issue by RamonGal** [quilljs/delta#91]
I am using the Quill editor and currently it works in development, but after building the project to production, the quill gives an error regarding the OpIterator.ts file:

```
runtime-core.esm-bundler.js:244 TypeError: Op_1$1.default.length is not a function
    at Iterator2.peekLength (Iterator.js:63:33)
    at Delta.js:259:55
    at Array.forEach (<anonymous>)
    at Delta2.diff (Delta.js:253:20)
    at internalModelEquals (vue-quill.esm-bundler.js:225:73)
    at watch.deep (vue-quill.esm-bundler.js:339:42)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at job (runtime-core.esm-bundler.js:1812:17)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:36)
```
    
from the following code at quilljs/delta/blob/main/src/OpIterator.ts:
    
```javascript

// built code
Iterator.prototype.peekLength = function () {
    if (this.ops[this.index]) {
        // Should never return 0 if our index is being managed correctly
        return Op_1.default.length(this.ops[this.index]) - this.offset;
    }
    else {
        return Infinity;
    }
};

// original code 
peekLength(): number {
  if (this.ops[this.index]) {
    // Should never return 0 if our index is being managed correctly
    return Op.length(this.ops[this.index]) - this.offset;
  } else {
    return Infinity;
  }
}
```

Meaning that the imported namespace for the Op doesn't work:
```javascript 
import AttributeMap from './AttributeMap';

interface Op {
  // only one property out of {insert, delete, retain} will be present
  insert?: string | Record<string, unknown>;
  delete?: number;
  retain?: number | Record<string, unknown>;

  attributes?: AttributeMap;
}

namespace Op {
  export function length(op: Op): number {
    if (typeof op.delete === 'number') {
      return op.delete;
    } else if (typeof op.retain === 'number') {
      return op.retain;
    } else if (typeof op.retain === 'object' && op.retain !== null) {
      return 1;
    } else {
      return typeof op.insert === 'string' ? op.insert.length : 1;
    }
  }
}

export default Op;
```

Im currently using vue-quill, that uses the versions:
  "quill": "^1.3.7",
  "quill-delta": "^4.2.2"

This is my compiler options, in case this comes from an incompatibility from Delta's es2015:

```
 "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "skipLibCheck": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "types": ["cypress", "node"],
    "outDir": "./built",
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"],
      "@components/*": ["./src/components/*"],
      "@services/*": ["./src/services/*"],
      "@views/*": ["./src/views/*"],
      "@utils/*": ["./src/utils/*"],
      "@stores/*": ["./src/stores/*"],
      "@apps/*": ["./src/apps/*"]
    },
    "ignoreDeprecations": "5.0"
  },
```

**Comment by RamonGal** [comment]
This seems to be an issue with the vue-quill package rather than the delta, please disconsider.
